//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSSite.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translator() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSSite.Resources.Translator", typeof(Translator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About us.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (USREOU 14360570, bank code 321842) Account No. 26004053023122.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BANKING CARD OF THE PROJECT IN PRIVATBANK 5169 3305 1527 4105.
        /// </summary>
        public static string BANKING_CARD {
            get {
                return ResourceManager.GetString("BANKING_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Business Assistance.
        /// </summary>
        public static string Business_Assistance {
            get {
                return ResourceManager.GetString("Business_Assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BUSINESSES.
        /// </summary>
        public static string BUSINESSES {
            get {
                return ResourceManager.GetString("BUSINESSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Businesses of veterans.
        /// </summary>
        public static string Businesses_of_veterans {
            get {
                return ResourceManager.GetString("Businesses_of_veterans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go over.
        /// </summary>
        public static string go_over {
            get {
                return ResourceManager.GetString("go_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Job vacancies.
        /// </summary>
        public static string jobs {
            get {
                return ResourceManager.GetString("jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KIND REGARDS, VETERANO SERVICE.
        /// </summary>
        public static string KIND_REGARDS {
            get {
                return ResourceManager.GetString("KIND_REGARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на en.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MENU.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There was nothing found on your request..
        /// </summary>
        public static string nothing_found {
            get {
                return ResourceManager.GetString("nothing_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We are on the map.
        /// </summary>
        public static string on_the_map {
            get {
                return ResourceManager.GetString("on_the_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our e-mail.
        /// </summary>
        public static string Our_email {
            get {
                return ResourceManager.GetString("Our_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our phone numbers.
        /// </summary>
        public static string Our_phone_numbers {
            get {
                return ResourceManager.GetString("Our_phone_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PARTNERS.
        /// </summary>
        public static string PARTNERS_titles {
            get {
                return ResourceManager.GetString("PARTNERS_titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Placing on the site.
        /// </summary>
        public static string Placing_on_the_site {
            get {
                return ResourceManager.GetString("Placing_on_the_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project assistance.
        /// </summary>
        public static string Project_assistance {
            get {
                return ResourceManager.GetString("Project_assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requisites.
        /// </summary>
        public static string Requisites {
            get {
                return ResourceManager.GetString("Requisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by city.
        /// </summary>
        public static string search_by_city {
            get {
                return ResourceManager.GetString("search_by_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by type.
        /// </summary>
        public static string search_by_type {
            get {
                return ResourceManager.GetString("search_by_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select search type.
        /// </summary>
        public static string select_search_type {
            get {
                return ResourceManager.GetString("select_search_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Since the creation of our project, it has been funded at our expense. It would be appropriate to say that we did not even think that it would turn into something more than just an informative site)). During the existence of the Veterano Service project, we organized fairs and forums that fostered the familiarity of the veterans and the development of their business. But the most important achievement is the cooperation of our participants from the whole country! It&apos;s a happiness - to bring together the best [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Since_the_creation {
            get {
                return ResourceManager.GetString("Since_the_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Site.
        /// </summary>
        public static string site {
            get {
                return ResourceManager.GetString("site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на So, in order to grow and develop, our project needs your help. Now you can become part of our project by financing the emergence of a new site. We invite you to grow and promote even more and better growth of the business of veterans. When transferring funds, please indicate &quot;charity&quot;..
        /// </summary>
        public static string So_in_order {
            get {
                return ResourceManager.GetString("So_in_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Useful.
        /// </summary>
        public static string useful {
            get {
                return ResourceManager.GetString("useful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USREOU DRFO 41837995 USREOU/SRNOU in PJSC CB &quot;PRIVATBANK&quot;.
        /// </summary>
        public static string USREOU {
            get {
                return ResourceManager.GetString("USREOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vacancies.
        /// </summary>
        public static string vacancies {
            get {
                return ResourceManager.GetString("vacancies", resourceCulture);
            }
        }
    }
}
